services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./services/todo-api/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: ./services/todo-api
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todo
      APP_VERSION: local-compose
    ports:
      - "3000:3000"
    depends_on:
      - db
